on:
  pull_request:
    branches:
      - master
name: ğŸš€ Deploy website
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v2.3.2

      - name: ğŸ”‘ Setup SSH private repositories access
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: ğŸ¶ Composer install
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --no-interaction --no-progress

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: ğŸ”— NPM install
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: ğŸ”¨ Build project
        run: npm run build

      - name: ğŸ—‘ï¸ Remove Node Modules
        run: rm -rf node_modules

      - name: ğŸ“‚ Deploy to server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.HOSTING_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: /www/dev.zateckymajak.cz/

      - name: ğŸ—‘ï¸ Remove Cache
        uses: JesseTG/rm@v1.0.2
        with:
          path: /www/dev.zateckymajak.cz/temp/cache
